language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t sla686/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sla686/docker-react npm run test

#For AWS deployment
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-921689218014"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY